export * from "./deleteDocument";
export * from "./getDocument";
export * from "./getSpecificDocuments";
export * from "./removeGroupAccess";
export * from "./removeUserAccess";
export * from "./updateDocumentName";
export * from "./updateDefaultAccess";
export * from "./updateGroupAccess";
export * from "./updateUserAccess";
